title: Ernest Benedito

baseurl: 
url: "https://ebeneditos.github.io" # change this to the base hostname & protocol for your site

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: "Ernest Benedito"
image: /icon.png
twitter:
  username: ebeneditos
linkedin:
  profile: ebeneditos
email: ebeneditos@gmail.com
